version: '3'

services:
  db:
    container_name: ${MONGOo_DB_NAME}
    image: mongo:6.0
    volumes: 
      - pokemon_vol:/data/db
    ports:
      - 27017:27017
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${USER_MONGO}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_PASS_MONGO}
    command: ['--auth']


volumes: 
  pokemon_vol:
    external: false